version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: mybestlife
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: mybestlife_db
    ports:
      - '6543:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: 
